version: '2.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bedrock_docker
    volumes:
      - mysql_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql
    build: .
    ports:
      - 9000:9000
    env_file:
      - ./bedrock/.env

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes_from:
      - wordpress:ro
    volumes:
      - ./.config/default.conf:/etc/nginx/conf.d/default.conf
      - ./bedrock/web/app/uploads:/var/www/html/web/app/uploads

volumes:
  mysql_data:
