version: '2.1'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    depends_on:
      - wordpress
    volumes_from:
      - wordpress:ro
    volumes:
      - ./.config/default.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    image: rjnay1984/bedrock-docker
    depends_on:
      - mysql
    build: .
    ports:
      - 9000:9000
    env_file:
      - ./wordpress/.env
    volumes:
      - ./wordpress:/var/www/html
      - ./themes:/var/www/html/web/app/themes

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bedrock_docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
