version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bedrock
    volumes:
      - mysql_data:/var/lib/mysql

  wordpress:
    image: bedrock
    restart: always
    depends_on:
      - mysql
    build: .
    ports:
      - 9000:9000
    env_file:
      - ./.env
    environment:
      DEPENDENCIES: >-
        timber/timber
        wpackagist-plugin/members
    volumes:
      - wordpress:/var/www/html
      - ./themes:/var/www/html/web/app/themes
      - ./config:/var/www/html/config

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - wordpress
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - wordpress:/var/www/html
      - ./themes:/var/www/html/web/app/themes
      - ./config:/var/www/html/config

volumes:
  mysql_data:
  wordpress:
